#!/bin/bash
# Post-installation script for Koii Settings
# This script integrates Koii Settings into the system after installation

set -e

echo "=== Koii Settings Post-Installation ==="

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Error: This script must be run as root"
    exit 1
fi

# Compile GSettings schemas
echo "Compiling GSettings schemas..."
if command -v glib-compile-schemas &> /dev/null; then
    glib-compile-schemas /usr/share/glib-2.0/schemas/
    echo "✓ GSettings schemas compiled"
else
    echo "⚠ Warning: glib-compile-schemas not found"
fi

# Update icon cache
echo "Updating icon cache..."
if command -v gtk-update-icon-cache &> /dev/null; then
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor/
    echo "✓ Icon cache updated"
else
    echo "⚠ Warning: gtk-update-icon-cache not found"
fi

# Update desktop database
echo "Updating desktop database..."
if command -v update-desktop-database &> /dev/null; then
    update-desktop-database /usr/share/applications/
    echo "✓ Desktop database updated"
else
    echo "⚠ Warning: update-desktop-database not found"
fi

# Update AppStream cache
echo "Updating AppStream cache..."
if command -v appstreamcli &> /dev/null; then
    appstreamcli refresh-cache --force || true
    echo "✓ AppStream cache updated"
else
    echo "⚠ Warning: appstreamcli not found"
fi

# Create Koii OS directories if they don't exist
echo "Setting up Koii OS directories..."
mkdir -p /opt/aios/config
mkdir -p /opt/aios/data
mkdir -p /opt/aios/logs
mkdir -p /var/lib/koii
mkdir -p /var/log/koii
echo "✓ Directories created"

# Set proper permissions
echo "Setting permissions..."
chmod 755 /opt/aios
chmod 755 /opt/aios/config
chmod 755 /opt/aios/data
chmod 755 /opt/aios/logs
chmod 755 /var/lib/koii
chmod 755 /var/log/koii
echo "✓ Permissions set"

# Create default configuration if it doesn't exist
CONFIG_FILE="/opt/aios/config/koii-settings.conf"
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Creating default configuration..."
    cat > "$CONFIG_FILE" << 'EOF'
# Koii Settings Configuration
# This file is automatically generated

[General]
FirstRun=true
Version=1.0.0

[Agents]
AutoStart=true
InitiativeLevel=medium

[Browser]
SemanticMode=true
PrivacyLevel=balanced

[Tasks]
MaxConcurrent=5
AutoRetry=true

[System]
LogLevel=info
ResourceLimit=80
EOF
    chmod 644 "$CONFIG_FILE"
    echo "✓ Default configuration created"
fi

# Register with GNOME Settings (if GNOME is installed)
if command -v gnome-shell &> /dev/null; then
    echo "Registering with GNOME Settings..."
    
    # The desktop file with X-GNOME-Settings-Panel should be enough
    # but we can also add it to the settings panels list
    SETTINGS_PANELS_DIR="/usr/share/gnome-control-center/panels"
    if [ -d "$SETTINGS_PANELS_DIR" ]; then
        ln -sf /usr/share/applications/org.koii.Settings.desktop \
               "$SETTINGS_PANELS_DIR/org.koii.Settings.desktop" 2>/dev/null || true
        echo "✓ Registered with GNOME Settings"
    fi
fi

# Create systemd user service for background monitoring (optional)
SYSTEMD_USER_DIR="/usr/lib/systemd/user"
if [ -d "$SYSTEMD_USER_DIR" ]; then
    echo "Creating systemd user service..."
    cat > "$SYSTEMD_USER_DIR/koii-monitor.service" << 'EOF'
[Unit]
Description=Koii OS Background Monitor
After=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 -m koii_os.automation.daemon
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
EOF
    chmod 644 "$SYSTEMD_USER_DIR/koii-monitor.service"
    echo "✓ Systemd service created"
    echo "  Users can enable it with: systemctl --user enable koii-monitor.service"
fi

# Print success message
echo ""
echo "=== Installation Complete ==="
echo ""
echo "Koii Settings has been successfully installed!"
echo ""
echo "You can now:"
echo "  • Open Settings → Koii Settings"
echo "  • Run 'koii-settings' from the command line"
echo "  • Find it in your application menu"
echo ""
echo "For more information, visit: https://github.com/koii-network/aios"
echo ""

exit 0

# Made with Bob
